export const Images = {
  logo: "/images/logo.webp",
  devLogo: "/images/platforms/dev-logo.webp",
  mediumLogo: "/images/platforms/medium-logo.webp",
  hashnodeLogo: "/images/platforms/hashnode-logo.webp",
  ghostLogo: "/images/platforms/ghost-logo.webp",
  wordpressLogo: "/images/platforms/wordpress-logo.webp",
  bloggerLogo: "/images/platforms/blogger-logo.webp",
  imagekitLogo: "/images/integrations/imagekit-logo.webp",
  unsplashLogo: "/images/integrations/unsplash-logo.webp",
  pexelsLogo: "/images/integrations/pexels-logo.webp",
  cloudinaryLogo: "/images/integrations/cloudinary-logo.webp",
  cloudinaryLogoIcon: "/images/integrations/cloudinary-logo-icon.webp",
  giphyLogo: "/images/integrations/giphy-logo.webp",
  poweredByGiphyDark: "/images/integrations/powered-by-giphy-dark.webp",
  poweredByGiphyLight: "/images/integrations/powered-by-giphy-light.webp",
};
