export const Images = {
  projectPage: "/images/demo/project-page-dark.png",
  logo: "/images/logo.webp",
  devLogo: "/images/platforms/dev-logo.webp",
  mediumLogo: "/images/platforms/medium-logo.webp",
  hashnodeLogo: "/images/platforms/hashnode-logo.webp",
  ghostLogo: "/images/platforms/ghost-logo.webp",
  wordpressLogo: "/images/platforms/wordpress-logo.webp",
  bloggerLogo: "/images/platforms/blogger-logo.webp",
  imagekitLogo: "/images/integrations/imagekit-logo.webp",
  unsplashLogo: "/images/integrations/unsplash-logo.webp",
  pexelsLogo: "/images/integrations/pexels-logo.webp",
  cloudinaryLogo: "/images/integrations/cloudinary-logo.webp",
  cloudinaryLogoIcon: "/images/integrations/cloudinary-logo-icon.webp",
  richTextEditing: "/images/demo/rich-text-editing.png",
  dictation: "/images/demo/dictation.png",
  toneAnalysis: "/images/demo/tone-analysis.png",
  importContent: "/images/demo/import-content.png",
  generativeAI: "/images/demo/generative-ai.png",
  og: "/images/og.png",
};
